/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.41
 * Generated at: 2021-03-11 09:18:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.io.PrintWriter;
import user.UserDAO;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.io.PrintWriter");
    _jspx_imports_classes.add("user.UserDAO");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("\t<meta http-equiv=\"content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\n");
      out.write("\t<title>강의평가 웹 사이트</title>\n");
      out.write("\t<link rel=\"stylesheet\" href=\"./css/bootstrap.min.css\">\n");
      out.write("\t<link rel=\"stylesheet\" href=\"./css/custom.css\">\n");
      out.write("</head>\n");
      out.write("<body>\n");

	String userID = null;
	if (session.getAttribute("userID") != null) {
		userID = (String) session.getAttribute("userID");
	}
	if (userID == null) {
		PrintWriter script = response.getWriter();
		script.println("<script>");
		script.println("alert('로그인을 해주세요.')");
		script.println("location.href='userLogin.jsp'");
		script.println("</script>");
		script.close();
	}
	boolean emailChecked = new UserDAO().getUserEmailChecked(userID);
	if (emailChecked == false) {
		PrintWriter script = response.getWriter();
		script.println("<script>");
		script.println("location.href='emailSendConfirm.jsp'");
		script.println("</script>");
		script.close();
	}

      out.write("\n");
      out.write("\t<nav class=\"navbar navbar=expand-lg navbar-light bg-light\">\n");
      out.write("\t\t<a class=\"navbar-brand\" href=\"index.jsp\">강의평가 웹 사이트</a>\n");
      out.write("\t\t<button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbar\">\n");
      out.write("\t\t\t<span class=\"navbar-toggler-icon\"></span>\n");
      out.write("\t\t</button>\n");
      out.write("\t\t<div id=\"navbar\" class=\"collapse navbar-collapse\">\n");
      out.write("\t\t\t<ul class=\"navbar-nav mr-auto\">\n");
      out.write("\t\t\t\t<li class=\"nav-item active\">\n");
      out.write("\t\t\t\t\t<a class=\"nav-link\" href=\"index.jsp\">메인</a>\n");
      out.write("\t\t\t\t</li>\n");
      out.write("\t\t\t\t<li class=\"nav-item dropdown\">\n");
      out.write("\t\t\t\t\t<a class=\"nav-link dropdown-toggle\" id=\"dropdown\" data-toggle=\"dropdown\">\n");
      out.write("\t\t\t\t\t\t회원 관리\n");
      out.write("\t\t\t\t\t</a>\n");
      out.write("\t\t\t\t\t<div class=\"dropdown-menu\" aria-labelledby=\"dropdown\">\n");

	if (userID == null) {

      out.write("\n");
      out.write("\t\t\t\t\t\t<a class=\"dropdown-item\" href=\"userLogin.jsp\">로그인</a>\n");
      out.write("\t\t\t\t\t\t<a class=\"dropdown-item\" href=\"userJoin.jsp\">회원가입</a>\n");

	} else {

      out.write("\n");
      out.write("\t\t\t\t\t\t<a class=\"dropdown-item\" href=\"userLogout.jsp\">로그아웃</a>\n");

	}

      out.write("\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</li>\n");
      out.write("\t\t\t</ul>\n");
      out.write("\t\t\t<form class=\"form-inline my-2 my-lg-0\">\n");
      out.write("\t\t\t\t<input class=\"form-control mr-sm-2\" type=\"search\" placeholder=\"내용을 입력하세요.\" aria-label=\"Search\">\n");
      out.write("\t\t\t\t<button class=\"btn btn-outline-success my-2 my-sm-0\" type=\"submit\">검색</button>\n");
      out.write("\t\t\t</form>\n");
      out.write("\t\t</div> \n");
      out.write("\t</nav>\n");
      out.write("\t\n");
      out.write("\t<section class=\"container\">\n");
      out.write("\t\t<form method=\"get\" action=\"./index.jsp\" class=\"form-inline mt-3\">\n");
      out.write("\t\t\t<select name=\"lectureDivide\" class=\"form-control mx-1 mt-2\">\n");
      out.write("\t\t\t\t<option value=\"전체\">전체</option>\n");
      out.write("\t\t\t\t<option value=\"전공\">전공</option>\n");
      out.write("\t\t\t\t<option value=\"교양\">교양</option>\n");
      out.write("\t\t\t\t<option value=\"기타\">기타</option>\n");
      out.write("\t\t\t</select>\n");
      out.write("\t\t\t<input type=\"text\" name=\"search\" class=\"form-control mx-1 mt-2\" placeholder=\"내용을 입력하세요.\">\n");
      out.write("\t\t\t<button type=\"submit\" class=\"btn btn=primary mx-1 mt-2\">검색</button>\n");
      out.write("\t\t\t<a class=\"btn btn-primary mx-1 mt-2\" data-toggle=\"modal\" href=\"#registerModal\">등록하기</a>\n");
      out.write("\t\t\t<a class=\"btn btn-danger mx-1 mt-2\" data-toggle=\"modal\" href=\"#reportmodal\">신고</a>\n");
      out.write("\t\t</form>\n");
      out.write("\t\t<div class=\"card bg-light mt-3\">\n");
      out.write("\t\t\t<div class=\"card-header bg-light\">\n");
      out.write("\t\t\t\t<div class=\"col-8 text-left\">컴퓨터개론&nbsp;<small>김예은</small></div>\n");
      out.write("\t\t\t\t<div class=\"col-4 text-right\">\n");
      out.write("\t\t\t\t\t종합<span style=\"color: red;\">A</span>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"card-body\">\n");
      out.write("\t\t\t\t<h5 class=\"card-title\">\n");
      out.write("\t\t\t\t\t정말 좋은 강의에요.&nbsp;<small>(2020년 가을학기)</small>\n");
      out.write("\t\t\t\t</h5>\n");
      out.write("\t\t\t\t<p class=\"card-text\"> 강의가 많이 널널해서, 솔직히 많이 배운 건 없는 것 같지만 학점도 아주 잘나오고 너무 좋은 것 같습니다.</p>\n");
      out.write("\t\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t\t<div class=\"col-9 text-left\">\n");
      out.write("\t\t\t\t\t\t성적<span style=\"color : red;\">A</span>\n");
      out.write("\t\t\t\t\t\t널널<span style=\"color : red;\">A</span>\n");
      out.write("\t\t\t\t\t\t강의<span style=\"color : red;\">C</span>\n");
      out.write("\t\t\t\t\t\t<span style=\"color : green;\">(추천 : 15)</span>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"col-3 text-right\">\n");
      out.write("\t\t\t\t\t\t<a onClick=\"return confirm('추천하시겠습니까?')\" href=\"./likeAction.jsp?evaluationID=\">추천</a>\n");
      out.write("\t\t\t\t\t\t<a onClick=\"return confirm('삭제하시겠습니까?')\" href=\"./deleteAction.jsp?evaluationID=\">삭제</a>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div class=\"card bg-light mt-3\">\n");
      out.write("\t\t\t<div class=\"card-header bg-light\">\n");
      out.write("\t\t\t\t<div class=\"col-8 text-left\">알고리즘&nbsp;<small>김영희</small></div>\n");
      out.write("\t\t\t\t<div class=\"col-4 text-right\">\n");
      out.write("\t\t\t\t\t종합<span style=\"color: red;\">A</span>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"card-body\">\n");
      out.write("\t\t\t\t<h5 class=\"card-title\">\n");
      out.write("\t\t\t\t\t정말 좋은 강의에요.&nbsp;<small>(2020년 가을학기)</small>\n");
      out.write("\t\t\t\t</h5>\n");
      out.write("\t\t\t\t<p class=\"card-text\"> 전공에서 아주 중요한 강의인 만큼 좋은 설명과 유용한 실습이 좋은 강의였습니다.</p>\n");
      out.write("\t\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t\t<div class=\"col-9 text-left\">\n");
      out.write("\t\t\t\t\t\t성적<span style=\"color : red;\">A</span>\n");
      out.write("\t\t\t\t\t\t널널<span style=\"color : red;\">B</span>\n");
      out.write("\t\t\t\t\t\t강의<span style=\"color : red;\">A</span>\n");
      out.write("\t\t\t\t\t\t<span style=\"color : green;\">(추천 : 50)</span>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"col-3 text-right\">\n");
      out.write("\t\t\t\t\t\t<a onClick=\"return confirm('추천하시겠습니까?')\" href=\"./likeAction.jsp?evaluationID=\">추천</a>\n");
      out.write("\t\t\t\t\t\t<a onClick=\"return confirm('삭제하시겠습니까?')\" href=\"./deleteAction.jsp?evaluationID=\">삭제</a>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</section>\n");
      out.write("\t\n");
      out.write("\t<div class=\"modal fade\" id=\"registerModal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"modal\" aria-hidden=\"true\">\n");
      out.write("\t\t<div class=\"modal-dialog\">\n");
      out.write("\t\t\t<div class=\"modal-content\">\n");
      out.write("\t\t\t\t<div class=\"modal-header\">\n");
      out.write("\t\t\t\t\t<h5 class=\"modal-title\" id=\"modal\">평가 등록</h5>\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\n");
      out.write("\t\t\t\t\t\t<span aria-hidden=\"true\">&times;</span>\n");
      out.write("\t\t\t\t\t</button>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"modal-body\">\n");
      out.write("\t\t\t\t\t<form action=\"./evaluationRegisterAction.jsp\" method=\"post\">\n");
      out.write("\t\t\t\t\t\t<div class=\"form-row\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group col-sm-6\">\n");
      out.write("\t\t\t\t\t\t\t\t<label>강의명</label>\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" name=\"lectureName\" class=\"form-control\" maxlength=\"20\">\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group col-sm-6\">\n");
      out.write("\t\t\t\t\t\t\t\t<label>교수명</label>\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" name=\"professorName\" class=\"form-control\" maxlength=\"20\">\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"form-row\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group col-sm-4\">\n");
      out.write("\t\t\t\t\t\t\t\t<label>수강 연도</label>\n");
      out.write("\t\t\t\t\t\t\t\t<select name=\"lectureYear\" class=\"form-control\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"2021\" selected>2021</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"2020\">2020</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"2019\">2019</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"2018\">2018</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"2017\">2017</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"2016\">2016</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"2015\">2015</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"2014\">2014</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"2013\">2013</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"2012\">2012</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"2011\">2011</option>\n");
      out.write("\t\t\t\t\t\t\t\t</select>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group col-sm-4\">\n");
      out.write("\t\t\t\t\t\t\t\t<label>수강 학기</label>\n");
      out.write("\t\t\t\t\t\t\t\t<select name=\"semesterDivide\" class=\"form-control\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"1학기\" selected>1학기</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"여름학기\">여름학기</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"2학기\">2학기</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"겨울학기\">겨울학기</option>\n");
      out.write("\t\t\t\t\t\t\t\t</select>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group col-sm-4\">\n");
      out.write("\t\t\t\t\t\t\t\t<label>강의 구분</label>\n");
      out.write("\t\t\t\t\t\t\t\t<select name=\"lectureDivide\" class=\"form-control\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"전공\" selected>전공</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"교양\">교양</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"기타\">기타</option>\n");
      out.write("\t\t\t\t\t\t\t\t</select>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t\t\t<label>제목</label>\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" name=\"evaluationTitle\" class=\"form-control\" maxlength=\"30\">\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t\t\t<label>내용</label>\n");
      out.write("\t\t\t\t\t\t\t<textarea name=\"evaluationContent\" class=\"form-control\" maxlength=\"2048\" style=\"height: 180px;\"></textarea>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"form-row\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group col-sm-3\">\n");
      out.write("\t\t\t\t\t\t\t\t<label>종합</label>\n");
      out.write("\t\t\t\t\t\t\t\t<select name=\"totalScore\" class=\"form-control\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"A\" selected>A</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"B\">B</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"C\">C</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"D\">D</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"F\">F</option>\n");
      out.write("\t\t\t\t\t\t\t\t</select>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group col-sm-3\">\n");
      out.write("\t\t\t\t\t\t\t\t<label>성적</label>\n");
      out.write("\t\t\t\t\t\t\t\t<select name=\"creditScore\" class=\"form-control\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"A\" selected>A</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"B\">B</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"C\">C</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"D\">D</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"F\">F</option>\n");
      out.write("\t\t\t\t\t\t\t\t</select>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group col-sm-3\">\n");
      out.write("\t\t\t\t\t\t\t\t<label>널널</label>\n");
      out.write("\t\t\t\t\t\t\t\t<select name=\"comfortableScore\" class=\"form-control\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"A\" selected>A</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"B\">B</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"C\">C</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"D\">D</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"F\">F</option>\n");
      out.write("\t\t\t\t\t\t\t\t</select>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group col-sm-3\">\n");
      out.write("\t\t\t\t\t\t\t\t<label>강의</label>\n");
      out.write("\t\t\t\t\t\t\t\t<select name=\"lectureScore\" class=\"form-control\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"A\" selected>A</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"B\">B</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"C\">C</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"D\">D</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"F\">F</option>\n");
      out.write("\t\t\t\t\t\t\t\t</select>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</form>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"modal-footer\">\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"btn btn-secondary\" data-dismiss=\"modal\">취소</button>\n");
      out.write("\t\t\t\t\t<button type=\"submit\" class=\"btn btn-primary\">등록하기</button>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\t\n");
      out.write("\t<div class=\"modal fade\" id=\"reportmodal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"modal\" aria-hidden=\"true\">\n");
      out.write("\t\t<div class=\"modal-dialog\">\n");
      out.write("\t\t\t<div class=\"modal-content\">\n");
      out.write("\t\t\t\t<div class=\"modal-header\">\n");
      out.write("\t\t\t\t\t<h5 class=\"modal-title\" id=\"modal\">신고하기</h5>\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"close\">\n");
      out.write("\t\t\t\t\t\t<span aria-hidden=\"true\">&times;</span>\n");
      out.write("\t\t\t\t\t</button>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"modal-body\">\n");
      out.write("\t\t\t\t\t<form action=\"./reportAction.jsp\" method=\"post\">\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t\t\t<label>신고 제목</label>\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" name=\"reportTitle\" class=\"form-control\" maxlength=\"30\">\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t\t\t<label>신고 내용</label>\n");
      out.write("\t\t\t\t\t\t\t<textarea name=\"reportContent\" class=\"form-control\" maxlength=\"2048\" style=\"height: 180px;\"></textarea>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t<div class=\"modal-footer\">\n");
      out.write("\t\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-secondary\" data-dismiss=\"modal\">취소</button>\n");
      out.write("\t\t\t\t\t\t\t<button type=\"submit\" class=\"btn btn-danger\">신고하기</button>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</form>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\t\n");
      out.write("\t<footer class=\"bg-dark mt-4 p-5 text-center\" style=\"color : #FFFFFF;\">\n");
      out.write("\t\tCopyright &copy; 2021 김예은 All Rights Reserved.\n");
      out.write("\t</footer>\n");
      out.write("\n");
      out.write("\t<script src=\"./js/jquery.min.js\"></script>\n");
      out.write("\t<script src=\"./js/popper.js\"></script>\n");
      out.write("\t<script src=\"./js/bootstrap.min.js\"></script>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
